### PR TITLE
adding xen host fixtures files for dev, test and production

### PR DESCRIPTION
**Pull request by si202cam**

### CODE REVIEW

**Comment by abrahammartin** [comment]
you are absolutelly right

**Comment by si202cam** [comment]
I moved the files into apimws....

**Comment by abrahammartin** [comment]
didn't @ph448 generate this fixtures via ansible using ansible vars?

**Comment by ph448** [comment]
@abrahammartin I did, but making this not hardcoded is very low priority compared to making it work, so not now

**Pull request merged**
